#!/bin/bash

# gnome-terminal
# /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@
# /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@
# /usr/bin/flatpak run md.obsidian.Obsidian
echo "" >> obsidian.path

obsidianRunCommand=$(cat obsidian.path);

ableToOpenExternalTerminal="1";

if [[ $obsidianRunCommand == "" ]];
then
    
    echo "opening new terminal"

    if x-terminal-emulator -e "bash -c 'echo -e \"\e[31mNo Obsidian path!\e[0m paste the executable path.\";	echo \"(On Linux) Right-click the Obsidian icon in the super-key menue > Properties > Copy the \\\"Command\\\" field.\"; read -p \"What is the executable command? \" ORC; echo \$ORC > obsidian.path;'"
    then
        # The popup window succesfully showed up!
        echo "popup terminal succesfully closed!"

    else
        # No support for opening new terminals
        echo -e "\e[31mUnable to open new terminal\e[0m"
        ableToOpenExternalTerminal="0";
    fi
    

    if [[ $ableToOpenExternalTerminal -ne "1" ]];
    then
        echo "..."
        echo -e "\e[31mNo Obsidian path!\e[0m paste the executable path.";

        read -p "What is the executable command? " ORC;
        echo $ORC > obsidian.path;
    fi


    while [[ $obsidianRunCommand == "" ]]
    do
        echo "reading user input..."
        sleep 1
        obsidianRunCommand=$(cat obsidian.path)
    done
fi

echo "";
echo "Opening $obsidianRunCommand";
echo "";

currentId=$(date '+%d');
gnome-terminal -- bash -c "echo \"$currentId\" > running.running; $obsidianRunCommand; echo \"-1\" > running.running"

runningId=$(cat running.running)
while [[ $runningId == $currentId ]]
do
    echo "Backing up obsidian at: ${PWD}"

    echo "(ADD)"

	git add .
    
    echo "(COMMIT)"

    currentId=$(date '+%d');
	dateString=$(date '+%d/%m/%Y %H:%M:%S');
	git commit -a -m "Backup $dateString"

    echo "(PULL)"

    git pull

    echo "(PUSH)"

	git push
	echo "Backup $dateString" >> BackupLog.running
	runningId=$(cat running.running)
	echo -e "\e[32mRunning SessionID\e[0m[$runningId] \e[32mExpected SessionID\e[0m[$currentId]"

    if [[ $runningId -ne "-1" ]];
    then
    	sleep 20
    fi

    printf "3 "
    sleep 1
    printf "2 "
    sleep 1
    echo "1"
    sleep 1
    
done



if [[ $runningId != "-1" ]]; then
	gnome-terminal -- bash -c "echo -e \"\e[31mDAILY SESSION EXPIRED!\e[0m Close Obsidian and re-open the backup program to start a new session\"; exec bash"
else
	gnome-terminal -- bash -c "echo -e \"\e[32mClosing Backup-Tool\e[0m dont wait for this window to close... Just close it already! \"; sleep 5;"
fi

read -p "Press [enter] to close..."

echo "-1" > running.running
