#!/bin/bash
cd ~/Documents/Obsidian/ObsidianBackups

# gnome-terminal
# /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@
# /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=obsidian.sh --file-forwarding md.obsidian.Obsidian @@u %U @@
# /usr/bin/flatpak run md.obsidian.Obsidian

rt=$(date '+%d');
gnome-terminal -x bash -c "echo \"$rt\" > running.txt; /usr/bin/flatpak run md.obsidian.Obsidian;cd ~/Documents/Obsidian/ObsidianBackups; exec bash"

while true
do
	git pull
	git add .
    
	dt=$(date '+%d/%m/%Y %H:%M:%S');
	git commit -a -m "Backup $dt"
	git push
	echo "Backup $dt" >> BackupLog.txt
	sleep 5
done

