#!/bin/bash
cd ~/Documents/Obsidian/ObsidianBackups

gnome-terminal

while true
do
    git pull
    git add -A
    dt=$(date '+%d/%m/%Y %H:%M:%S');
    git commit -a -m "Backup $dt"
    git push
    echo "Backup $dt"
    sleep 5
done
